name: "TestDrive_Build"

on: [push]

env:
  AZURE_WEBAPP_NAME: af-linuxapp #set this to your application name
  AZURE_WEBAPP_PACKAGE_PATH: "./published" #set this to the path of you WebApp
  NETCORE_VERSION: "3.1.103"


jobs:
  build:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/checkout@v2

    - name: Setup .NET Core SDK ${{env.NETCORE_VERSION}}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.NETCORE_VERSION}}

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Publish
      run: dotnet publish --no-build -c Release -o ${{ env.AZURE_WEBAPP_SECRET}}

    - name: "Deploy to Azure WebApp"
      run: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{secret.AZURE_WEBAPP_PUBLISH_PROFILE}} 
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

       